// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgo-CIhYLdUdeONAFbqX000ZQwb8K2ruU',
    appId: '1:78713240649:android:4acaa02728c032036ad398',
    messagingSenderId: '78713240649',
    projectId: 'mentora-e5e5c',
    storageBucket: 'mentora-e5e5c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPE455AMUSVPcEVHXlzOzLBQjSyg0N9w',
    appId: '1:78713240649:ios:06407b61ce85af046ad398',
    messagingSenderId: '78713240649',
    projectId: 'mentora-e5e5c',
    storageBucket: 'mentora-e5e5c.firebasestorage.app',
    iosBundleId: 'com.example.mentora',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4-b843cY9JB8uXCuabFrTK3n6RcH-7o',
    appId: '1:78713240649:web:22d54fbd8fe791a96ad398',
    messagingSenderId: '78713240649',
    projectId: 'mentora-e5e5c',
    authDomain: 'mentora-e5e5c.firebaseapp.com',
    storageBucket: 'mentora-e5e5c.firebasestorage.app',
    measurementId: 'G-ZVPZYDTS46',
  );
}
